package com.rule

import com.roche.infinity.system.SystemProperties

rule "Windows 10 with no service pack"
	when 
		systemProperties: SystemProperties(operatingSystemName=="Windows 10" && servicePack==null)
	then	
		systemProperties.setCompatible(true);
	end

rule "Windows Server 2008 R2 with Service Pack 1"
	when 
		systemProperties: SystemProperties(operatingSystemName=="Windows Server 2008 R2" && servicePack=="SP1")
	then	
		systemProperties.setCompatible(true);
	end
	
rule "Windows Server 2012 R2 with no service pack"
	when 
		systemProperties: SystemProperties(operatingSystemName=="Windows Server 2012" && servicePack==null)
	then	
		systemProperties.setCompatible(true);
	end